"use server";

import { createClient } from "@/lib/supabase/server";
import { revalidatePath } from "next/cache";

export interface CreatePatientInput {
  // New 3-part name fields (full_name is generated by DB)
  first_name: string;
  middle_name?: string | null;
  last_name?: string | null;
  first_name_ar?: string | null;
  middle_name_ar?: string | null;
  last_name_ar?: string | null;
  dob?: string;
  gender?: "male" | "female";
  phone: string;
  phone2?: string;
  phone2_relation?: string;
  address?: string;
  email?: string;
  national_id?: string;
  mrn?: string;
  blood_type?: string;
  mrn?: string | null;
  allergies?: string;
}

export interface CreatePatientResult {
  success: boolean;
  patientId?: string;
  error?: string;
}

/**
 * Creates a new patient record.
 *
 * clinic_id is NOT taken from the client — it's looked up server-side from
 * the logged-in user's own row, so there's no way for a request to inject
 * a different clinic_id and create a patient under someone else's tenant.
 * RLS provides a second layer of defense even if this check were bypassed.
 */
export async function createPatient(
  input: CreatePatientInput
): Promise<CreatePatientResult> {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return { success: false, error: "Not authenticated." };
  }

  if (!input.first_name?.trim()) {
    return { success: false, error: "First name is required." };
  }
  if (!input.phone?.trim()) {
    return { success: false, error: "Phone number is required." };
  }

  // Look up the caller's own clinic_id — never trust a client-supplied value.
  const { data: profile, error: profileError } = await supabase
    .from("users")
    .select("clinic_id")
    .eq("id", user.id)
    .single();

  if (profileError || !profile) {
    return { success: false, error: "Could not resolve your clinic. Try logging in again." };
  }

  const { data, error } = await supabase
    .from("patients")
    .insert({
      clinic_id: profile.clinic_id,
      full_name:      [input.first_name, input.middle_name, input.last_name].filter(Boolean).join(" ").trim(),
      first_name:     input.first_name.trim(),
      middle_name:    input.middle_name?.trim() || null,
      last_name:      input.last_name?.trim() || null,
      first_name_ar:  input.first_name_ar?.trim() || null,
      middle_name_ar: input.middle_name_ar?.trim() || null,
      last_name_ar:   input.last_name_ar?.trim() || null,
      dob: input.dob || null,
      gender: input.gender || null,
      phone: input.phone.trim(),
      phone2: input.phone2?.trim() || null,
      phone2_relation: input.phone2_relation?.trim() || null,
      address: input.address?.trim() || null,
      email: input.email?.trim() || null,
      national_id: input.national_id?.trim() || null,
      mrn: input.mrn?.trim() || null,
      blood_type: input.blood_type || null,
      mrn: input.mrn?.trim() || null,
      allergies: input.allergies?.trim() || null,
    })
    .select("id")
    .single();

  if (error) {
    return { success: false, error: error.message };
  }

  revalidatePath("/patients");

  return { success: true, patientId: data.id };
}

export interface UpdatePatientInput {
  first_name?: string;
  middle_name?: string | null;
  last_name?: string | null;
  first_name_ar?: string | null;
  middle_name_ar?: string | null;
  last_name_ar?: string | null;
  phone?: string;
  phone2?: string;
  phone2_relation?: string;
  dob?: string;
  gender?: "male" | "female";
  address?: string;
  email?: string;
  blood_type?: string;
  mrn?: string | null;
  allergies?: string;
  insurance_company_id?: string;
  insurance_policy_number?: string;
  insurance_expiry_date?: string;
}

export async function updatePatient(
  patientId: string,
  input: UpdatePatientInput
): Promise<CreatePatientResult> {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) return { success: false, error: "Not authenticated." };

  const { error } = await supabase
    .from("patients")
    .update({
      full_name:      input.first_name ? [input.first_name, input.middle_name, input.last_name].filter(Boolean).join(" ").trim() : undefined,
      first_name:     input.first_name?.trim(),
      middle_name:    input.middle_name?.trim() || null,
      last_name:      input.last_name?.trim() || null,
      first_name_ar:  input.first_name_ar?.trim() || null,
      middle_name_ar: input.middle_name_ar?.trim() || null,
      last_name_ar:   input.last_name_ar?.trim() || null,
      phone: input.phone?.trim(),
      phone2: input.phone2?.trim() || null,
      phone2_relation: input.phone2_relation?.trim() || null,
      dob: input.dob || null,
      gender: input.gender || null,
      address: input.address?.trim() || null,
      email: input.email?.trim() || null,
      blood_type: input.blood_type || null,
      mrn: input.mrn?.trim() || null,
      allergies: input.allergies?.trim() || null,
      insurance_company_id: input.insurance_company_id || null,
      insurance_policy_number: input.insurance_policy_number?.trim() || null,
      insurance_expiry_date: input.insurance_expiry_date || null,
    })
    .eq("id", patientId);

  if (error) return { success: false, error: error.message };

  revalidatePath("/secretary/patients");
  return { success: true };
}
